version: '3.8'

services:
  rest-api:
    container_name: rest-api
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      - PORT=${PORT}
    volumes:
      - .:/usr/app/src
    restart: always
    networks:
      - postgres
  db:
    container_name: db
    build: ./DB/
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/lib/postgresql
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    networks:
      - postgres
volumes:
  pgdata:
  pglogs:
networks:
  postgres:
    name: postgres
    driver: bridge